name: Auto Test & Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl

    - name: Run tests & generate report
      run: python run_all.py

    - name: Send report to DingTalk (带加签)
      env:
        DING_WEBHOOK_BASE: ${{ secrets.DING_WEBHOOK }}   # 仅 https://oapi.dingtalk.com/robot/send?access_token=xxx
        DING_SECRET: ${{ secrets.DING_SECRET }}          # SECxxxx...
      run: |
        # 生成官方要求的时间戳 & 签名
        timestamp=$(date +%s000)
        string_to_sign="${timestamp}\n${DING_SECRET}"
        sign=$(echo -n -e "$string_to_sign" | openssl dgst -sha256 -hmac "$DING_SECRET" -binary | base64 | tr '+/' '-_' | tr -d '=')

        # 组装最终 webhook
        webhook="${DING_WEBHOOK_BASE}&timestamp=${timestamp}&sign=${sign}"

        # 发送 markdown
        curl "$webhook" \
          -H 'Content-Type: application/json' \
          -d "$(jq -n \
                --arg title "接口自动化报告" \
                --arg text  "$(cat report.md)" \
                '{msgtype:"markdown",markdown:{title:$title,text:$text}}')"