name: Auto Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl

    - name: Run tests
      run: python run_all.py