name: Auto Test & Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl

    - name: Run tests & generate report
      run: python run_all.py

    - name: Send report to DingTalk (with sign)
      env:
        DING_WEBHOOK_BASE: ${{ secrets.DING_WEBHOOK }}   # 原始地址，不含时间戳
        DING_SECRET: ${{ secrets.DING_SECRET }}
      run: |
        # 生成时间戳 & 签名
        timestamp=$(date +%s000)
        string_to_sign="$timestamp\n$DING_SECRET"
        sign=$(echo -n "$string_to_sign" | openssl dgst -sha256 -hmac "$DING_SECRET" -binary | base64 | tr '+/' '-_' | tr -d '=')
        # 组装完整 webhook
        webhook="${DING_WEBHOOK_BASE}&timestamp=${timestamp}&sign=${sign}"
        # 推送 markdown
        curl "$webhook" \
          -H 'Content-Type: application/json' \
          -d "{\"msgtype\":\"markdown\",\"markdown\":{\"title\":\"接口自动化报告\",\"text\":\"$(sed ':a;N;$!ba;s/\n/\\n/g' report.md)\"}}"