name: Auto Test & Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl

    - name: Run tests & generate report
      run: python run_all.py

    - name: Send DingTalk with sign
      env:
        TOKEN: ${{ secrets.DING_WEBHOOK }}          # https://oapi.dingtalk.com/robot/send?access_token=XXX
        SECRET: ${{ secrets.DING_SECRET }}          # SECxxxxxxxxxxxxxxxxxxxxxxxxxx
      run: |
        # ========= 官方公式计算 =========
        timestamp=$(date +%s000)
        sign=$(echo -n "$timestamp"$'\n'"$SECRET" | \
               openssl dgst -sha256 -hmac "$SECRET" -binary | \
               base64 | tr '+/' '-_' | tr -d '=')

        url="${TOKEN}&timestamp=${timestamp}&sign=${sign}"
        # =================================

        # 发送 Markdown
        curl "$url" \
          -H 'Content-Type: application/json' \
          -d "$(jq -n \
                --arg title "接口自动化报告" \
                --arg text  "$(cat report.md)" \
                '{msgtype:"markdown",markdown:{title:$title,text:$text}}')"